name: release
on:
  push:
    branches: ["main"]

jobs:

  release-stage:
    runs-on: ubuntu-latest
    environment: stag
    steps:
      - name: echo
        run: echo "Hello World from stage"
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 16.0.0
          branches: |
            [main]
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  release-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: [release-stage]
    steps:
      - name: echo
        run: echo "Hello World from stage"
  

